// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepsApi.Models;

namespace RepsApi.Migrations
{
    [DbContext(typeof(WorkoutDayContext))]
    [Migration("20191113031311_MORETABLES")]
    partial class MORETABLES
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RepsApi.Models.Set", b =>
                {
                    b.Property<long>("SetId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Reps");

                    b.Property<long?>("StationSetId");

                    b.Property<int>("Weight");

                    b.HasKey("SetId");

                    b.HasIndex("StationSetId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("RepsApi.Models.Station", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("RepsApi.Models.StationSet", b =>
                {
                    b.Property<long>("StationSetId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("StationFK");

                    b.Property<long?>("WorkoutId");

                    b.HasKey("StationSetId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("StationSets");
                });

            modelBuilder.Entity("RepsApi.Models.Workout", b =>
                {
                    b.Property<long>("WorkoutId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("WorkoutDayFK");

                    b.HasKey("WorkoutId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("RepsApi.Models.WorkoutDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<bool>("IsComplete");

                    b.HasKey("Id");

                    b.ToTable("WorkoutDays");
                });

            modelBuilder.Entity("RepsApi.Models.Set", b =>
                {
                    b.HasOne("RepsApi.Models.StationSet")
                        .WithMany("Sets")
                        .HasForeignKey("StationSetId");
                });

            modelBuilder.Entity("RepsApi.Models.StationSet", b =>
                {
                    b.HasOne("RepsApi.Models.Workout")
                        .WithMany("StationSets")
                        .HasForeignKey("WorkoutId");
                });
#pragma warning restore 612, 618
        }
    }
}
